version: '3.4'

services:

  redisdb:
    image: redis

  rabbitmq:
    image: rabbitmq:3-management-alpine

  hasin.api:
    image: ${DOCKER_REGISTRY-}hasin.api
    build:
      context: .
      dockerfile: src/Presentation/Hasin.API/Dockerfile

  hasin.publicher.api:
    image: ${DOCKER_REGISTRY-}hasin.publicher.api
    build:
      context: .
      dockerfile: src/Presentation/Hasin.PublicherAPI/Dockerfile

#  hasin.unit.test:
#    image: ${DOCKER_REGISTRY-}hasin.unit.test
#    build:
#      context: .
#      dockerfile: src/Test/UnitTest/Dockerfile

      

      


