version: '3.4'

services:

  redisdb:
    image: redis

  rabbitmq:
    image: rabbitmq:3-management-alpine

  hasin.api:
    image: ${DOCKER_REGISTRY-}identity
    build:
      context: .
      dockerfile: src/Presentation/Hasin.API/Dockerfile
      

      


